Traceback (most recent call last):
  File "/Users/donkang/./streams_err.py", line 5, in <module>
    raise ValueError("Now we generate an error to STDERR")
ValueError: Now we generate an error to STDERR
This will come from STDIN: Now we write it to STDOUT: Don't mind me, just a bit of text here...
